contact_links:
  - name: Discord Community Support
    url: https://discord.gg/ktypkdpkDz
    about: Issue tracker is for bug reports only. If you need help, go to Discussions or join our Discord server.
blank_issues_enabled: false
