contact_links:
  - name: Discord Community Support
    url: https://discord.com/invite/GaczkwfgV9
    about: Issue tracker is for bug reports only. If you need help, go to Discussions or join our Discord server.